# Generated by Django 3.0 on 2019-12-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery', '0003_auto_20191215_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('images', models.ManyToManyField(to='image_gallery.Image')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
